### ISSUE TITLE
Contrast ratio

### ISSUE THREAD

**Issue by SinimaWath** [BMSTU-Schedule/web#1]
Слишком маленький contrast ratio, между шрифтом и background: 2,54. Это делает сайт абсолютно недоступным
[Немного инфы](https://a11yproject.com/posts/what-is-color-contrast/)
Минимальный ratio: 4,5
Используете хотя бы #717171, цвет для шрифта.
P.S. Contrast ratio  можно посмотреть в devTools

**Comment by gabolaev** [comment]
У нас планируется редизайн. Учтём там. Спасибо

**Comment by SinimaWath** [comment]
Хорошо :) Когда будуете верстать, не забывайте, пожалуйста, про a11y
